### PR TITLE
Weird warning in birkhoff example

### PR DESCRIPTION
**Pull request by dhendryc**
See issue #94 

It looks like a Bonobo warning. But I added a bunch of prints to locate there exactly it is thrown and it seems to be in the `blended_pariwise_conditional_gradient`. 

There is no such warning in our fw_callback and, as far as I have seen, also not in the Bonobo source code.

Could this be from SCIP?

### CODE REVIEW

**Comment by matbesancon** [comment]
`blended_pariwise_conditional_gradient` has no such warning I think?

**Comment by matbesancon** [comment]
Yes indeed:
```
scip-dev/scip/src/scip/primal.c
666:         SCIPmessagePrintWarning(messagehdlr, "Dual bound %g is larger than the objective of the primal solution %g. The solution might not be optimal.\n",
```
https://github.com/scipopt/scip/blob/master/src/scip/primal.c#L666

**Comment by matbesancon** [comment]
Ideally we should try to extract which problem is solved at that point that generates this issue, to report it to SCIP but that's it

**Comment by dhendryc** [comment]
This is a SCIP issue. Seems like some parameters are not reset in between solves. Will be transferred to SCIP.

**Pull request closed without merging**
