### PR TITLE
Fixing issue with post solve

### PR DESCRIPTION
**Pull request by dhendryc**
In some instances, the post solve produced a worse solution than the current incumbent. 

This was due to nearly integer points (e.g. `1 + 2e-10`) being evaluated by a strongly convex (or sharp) objective function.

### CODE REVIEW

**Comment by dhendryc** [comment]
- [ ] Wait for benchmarks to pass

**Comment by dhendryc** [comment]
I added a function that is basically like a mini-postsolve for each new solution. This is, however, rather costly and thus disabled by default. This only really makes sense  if we use a MIP solver, I think. The combinatorial BLMOs usually return exact integer vertices anyway. 

@matbesancon I am not sure if this is the cleanest way to do it though.

**Comment by matbesancon** [comment]
what's the reason a simplex descent step would use a non-vertex? It should be using the same vertices as other lazy steps

**Comment by dhendryc** [comment]
The function starting here https://github.com/ZIB-IOL/FrankWolfe.jl/blob/a53609b23768eae00b2c029c075acc01e8f5f6ee/src/blended_cg.jl#L896 does not necessarily return a vertex. From what I understand `y` is some point in the convex combination.

**Comment by dhendryc** [comment]
Round the solutions of the subproblems.

**Review by matbesancon — APPROVED** [review]

**Pull request merged**
